# Generated by Django 4.2.20 on 2025-04-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RackitoMap', '0002_emailverification_delete_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес, полученный с помощью обратного геокодирования.', null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='point',
            name='point_type',
            field=models.CharField(choices=[('event', 'Событие')], default='event', help_text='Тип метки на карте (например, событие, место).', max_length=50, verbose_name='Тип точки'),
        ),
    ]
