# Generated by Django 4.2.20 on 2025-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RackitoMap', '0003_point_address_point_point_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='marker_image',
        ),
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес, полученный через обратное геокодирование.', max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
