# Generated by Django 4.2.20 on 2025-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RackitoMap', '0004_remove_point_marker_image_alter_point_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес, полученный с помощью обратного геокодирования.', null=True, verbose_name='Адрес'),
        ),
    ]
